### ISSUE TITLE
ModuleNotFoundError: No module named 'RegisterHook'

### ISSUE THREAD

**Issue by pppppkun** [20000yshust/Backdoor-Defense-Via-Suppressing-Model-Shortcuts#1]
```
python train_backdoormodel.py --model=resnet18 --datasets=cifar10 --attack=badnets --target=1 --poisoned_rate=0.1 --mp=experiments --gpu=0
Traceback (most recent call last):
  File "train_backdoormodel.py", line 14, in <module>
    from RegisterHook import train_register_forwardhook_for_resnet
ModuleNotFoundError: No module named 'RegisterHook'
```

**Comment by 20000yshust** [comment]
Thanks for your issue. I am sorry that I have made an omission when I upload the codes. The Module RegisrerHook is enclosed. I will modify this problem on github later. May you give me a star of this project? Thanks!


Best,
Sheng Yang




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "20000yshust/Backdoor-Defense-Via-Suppressing-Model-Shortcuts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 下午3:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[20000yshust/Backdoor-Defense-Via-Suppressing-Model-Shortcuts] ModuleNotFoundError: No module named 'RegisterHook' (Issue #1)





 python train_backdoormodel.py --model=resnet18 --datasets=cifar10 --attack=badnets --target=1 --poisoned_rate=0.1 --mp=experiments --gpu=0 Traceback (most recent call last):   File "train_backdoormodel.py", line 14, in <module&gt;     from RegisterHook import train_register_forwardhook_for_resnet ModuleNotFoundError: No module named 'RegisterHook'

**Comment by pppppkun** [comment]
> Thanks for your issue. I am sorry that I have made an omission when I upload the codes. The Module RegisrerHook is enclosed. I will modify this problem on github later. May you give me a star of this project? Thanks! Best, Sheng Yang
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "20000yshust/Backdoor-Defense-Via-Suppressing-Model-Shortcuts" ***@***.***&gt;; 发送时间:&nbsp;2023年6月26日(星期一) 下午3:28 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[20000yshust/Backdoor-Defense-Via-Suppressing-Model-Shortcuts] ModuleNotFoundError: No module named 'RegisterHook' (Issue #1) python train_backdoormodel.py --model=resnet18 --datasets=cifar10 --attack=badnets --target=1 --poisoned_rate=0.1 --mp=experiments --gpu=0 Traceback (most recent call last): File "train_backdoormodel.py", line 14, in <module&gt; from RegisterHook import train_register_forwardhook_for_resnet ModuleNotFoundError: No module named 'RegisterHook' — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

Thank you for your reply, of course!
