### ISSUE TITLE
 Error: ModuleNotFoundError: 'RegisterHook' in train_backdoormodel.py

### ISSUE THREAD

**Issue by LandAndLand** [20000yshust/Backdoor-Defense-Via-Suppressing-Model-Shortcuts#2]
I hope this message finds you well. I encountered an issue while attempting to run the train_backdoormodel.py script in my environment. Below is the traceback of the error I encountered:
`Traceback (most recent call last):
  File "train_backdoormodel.py", line 14, in <module>
    from RegisterHook import train_register_forwardhook_for_resnet
ModuleNotFoundError: No module named 'RegisterHook'`

**Comment by 20000yshust** [comment]
Thanks for your remind.

**Comment by 20000yshust** [comment]
You can just skip this part and it is not used in the codes. The register hook is used for the experiments in the Section 2 of paper. Could you give me a star on github? Thanks
